function ss=SSFinder_HIV(coef)
math('$Version')
math('matlab2math','coefdidan1', coef.a_L);
math('coefdidan1=coefdidan1[[1,1]]');
math('matlab2math','coefdidan2', coef.g_AI);
math('coefdidan2=coefdidan2[[1,1]]');
math('matlab2math','coefdidan3', coef.g_AV);
math('coefdidan3=coefdidan3[[1,1]]');
math('matlab2math','coefdidan4', coef.g_E0AV);
math('coefdidan4=coefdidan4[[1,1]]');
math('matlab2math','coefdidan5', coef.g_EI);
math('coefdidan5=coefdidan5[[1,1]]');
math('matlab2math','coefdidan6', coef.g_LI);
math('coefdidan6=coefdidan6[[1,1]]');
math('matlab2math','coefdidan7', coef.g_LV);
math('coefdidan7=coefdidan7[[1,1]]');
math('matlab2math','coefdidan8', coef.g_QAV);
math('coefdidan8=coefdidan8[[1,1]]');
math('matlab2math','coefdidan9', coef.mu_A);
math('coefdidan9=coefdidan9[[1,1]]');
math('matlab2math','coefdidan10', coef.mu_C);
math('coefdidan10=coefdidan10[[1,1]]');
math('matlab2math','coefdidan11', coef.mu_E);
math('coefdidan11=coefdidan11[[1,1]]');
math('matlab2math','coefdidan12', coef.mu_E0);
math('coefdidan12=coefdidan12[[1,1]]');
math('matlab2math','coefdidan13', coef.mu_I);
math('coefdidan13=coefdidan13[[1,1]]');
math('matlab2math','coefdidan14', coef.mu_L);
math('coefdidan14=coefdidan14[[1,1]]');
math('matlab2math','coefdidan15', coef.mu_Q);
math('coefdidan15=coefdidan15[[1,1]]');
math('matlab2math','coefdidan16', coef.mu_U);
math('coefdidan16=coefdidan16[[1,1]]');
math('matlab2math','coefdidan17', coef.mu_V);
math('coefdidan17=coefdidan17[[1,1]]');
math('matlab2math','coefdidan18', coef.n_E1);
math('coefdidan18=coefdidan18[[1,1]]');
math('matlab2math','coefdidan19', coef.n_E2);
math('coefdidan19=coefdidan19[[1,1]]');
math('matlab2math','coefdidan20', coef.n_Q1);
math('coefdidan20=coefdidan20[[1,1]]');
math('matlab2math','coefdidan21', coef.n_Q2);
math('coefdidan21=coefdidan21[[1,1]]');
math('matlab2math','coefdidan22', coef.nu_I);
math('coefdidan22=coefdidan22[[1,1]]');
math('matlab2math','coefdidan23', coef.p_E);
math('coefdidan23=coefdidan23[[1,1]]');
math('matlab2math','coefdidan24', coef.p_L);
math('coefdidan24=coefdidan24[[1,1]]');
math('matlab2math','coefdidan25', coef.r_A);
math('coefdidan25=coefdidan25[[1,1]]');
math('matlab2math','coefdidan26', coef.r_E0);
math('coefdidan26=coefdidan26[[1,1]]');
math('matlab2math','coefdidan27', coef.sigma_I);
math('coefdidan27=coefdidan27[[1,1]]');
math('matlab2math','coefdidan28', coef.w_C);
math('coefdidan28=coefdidan28[[1,1]]');
math('matlab2math','coefdidan29', coef.w_U);
math('coefdidan29=coefdidan29[[1,1]]');
math('matlab2math','coefdidan30', coef.g_CV);
math('coefdidan29=coefdidan30[[1,1]]');
math('advardidan2=coefdidan4*vardidan5*vardidan1*vardidan4');
math('advardidan4=coefdidan8*vardidan6*vardidan1*vardidan4');
math('advardidan6=coefdidan22*vardidan3');
math('advardidan1=(1-coefdidan24)*coefdidan3*vardidan1*vardidan4+coefdidan2*vardidan1*vardidan3+coefdidan6*vardidan2*vardidan3+coefdidan1*vardidan2');
math('advardidan3=coefdidan4*vardidan5*vardidan1*vardidan4');
math('advardidan5=coefdidan8*vardidan6*vardidan1*vardidan4');
math('y1=coefdidan25-coefdidan9*vardidan1-coefdidan3*vardidan1*vardidan4-coefdidan2*vardidan1*vardidan3 == 0');
math('y2=-(coefdidan14+coefdidan1)*vardidan2-coefdidan6*vardidan2*vardidan3+coefdidan24*coefdidan3*vardidan1*vardidan4 == 0');
math('y3=-(coefdidan13+coefdidan27*coefdidan22)*vardidan3-coefdidan5*vardidan7*vardidan3+Exp[-coefdidan10*coefdidan28]*advardidan1 == 0'); %
math('y4=-coefdidan17*vardidan4-coefdidan3*vardidan1*vardidan4-coefdidan7*vardidan2*vardidan4+Exp[-coefdidan16*coefdidan29]*advardidan6 - advardidan1*vardidan4*coefdidan30 *(1 - Exp[-coefdidan10*coefdidan28])/ coefdidan10 == 0');
math('y5=coefdidan26-coefdidan12*vardidan5-advardidan2 == 0');
math('y6=-coefdidan15*vardidan6-advardidan4+coefdidan20*advardidan3+coefdidan21*advardidan5 == 0');
math('y7=-coefdidan11*vardidan7-coefdidan23*coefdidan5*vardidan7*vardidan3+coefdidan18*advardidan3+coefdidan19*advardidan5 == 0');
math('res = NSolve[{y1, y2, y3, y4, y5, y6, y7, vardidan1 >=0, vardidan2 >=0, vardidan3 >=0, vardidan4 >=0, vardidan5 >=0, vardidan6 >=0, vardidan7 >=0}, {vardidan1, vardidan2, vardidan3, vardidan4, vardidan5, vardidan6, vardidan7}, Reals]');
ss = math('math2matlab','{vardidan1, vardidan2, vardidan3, vardidan4, vardidan5, vardidan6, vardidan7}/.res');
math('quit')
